name: news_final
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # ? Local NoSQL Database (Version: 2.1.1)
  sembast:
  # ? Gives Native Path to Application Directory (Version: 1.4.5)
  path_provider:
  # ? For Ease Development of Bloc (Version: 2.1.1)
  flutter_bloc:
  # ? Provides Value Equality in Dart (Version: 1.0.1)
  equatable:
  # ? Awesome Loading Animation (Version: 1.0.2)
  loading:
  # ? for http req and res (Version: 0.12.0+2)
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    